// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import LightboxController from "./lightbox_controller.js"
application.register("lightbox", LightboxController)

import LikenessUploaderController from "./likeness_uploader_controller.js"
application.register("likeness-uploader", LikenessUploaderController)

import MessagesController from "./messages_controller.js"
application.register("messages", MessagesController)

import ModalController from "./modal_controller.js"
application.register("modal", ModalController)

import NapcController from "./napc_controller.js"
application.register("napc", NapcController)

import NavbarController from "./navbar_controller.js"
application.register("navbar", NavbarController)

import PlayerController from "./player_controller.js"
application.register("player", PlayerController)

import PronunciationFormController from "./pronunciation_form_controller.js"
application.register("pronunciation-form", PronunciationFormController)

import RecorderController from "./recorder_controller.js"
application.register("recorder", RecorderController)

import UrlController from "./url_controller.js"
application.register("url", UrlController)
