// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import LightboxController from "./lightbox_controller"
application.register("lightbox", LightboxController)

import LikenessUploaderController from "./likeness_uploader_controller"
application.register("likeness-uploader", LikenessUploaderController)

import MessagesController from "./messages_controller"
application.register("messages", MessagesController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import NapcController from "./napc_controller"
application.register("napc", NapcController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import PlayerController from "./player_controller"
application.register("player", PlayerController)

import PronounFormController from "./pronoun_form_controller"
application.register("pronoun-form", PronounFormController)

import PronunciationFormController from "./pronunciation_form_controller"
application.register("pronunciation-form", PronunciationFormController)

import PublicProfileController from "./public_profile_controller"
application.register("public-profile", PublicProfileController)

import RecorderController from "./recorder_controller"
application.register("recorder", RecorderController)

import RubyUi__DropdownMenuController from "./ruby_ui/dropdown_menu_controller"
application.register("ruby-ui--dropdown-menu", RubyUi__DropdownMenuController)

import RubyUi__ThemeToggleController from "./ruby_ui/theme_toggle_controller"
application.register("ruby-ui--theme-toggle", RubyUi__ThemeToggleController)

import UrlController from "./url_controller"
application.register("url", UrlController)
