FROM ruby:3.1.3

COPY vendor/prepare-env.sh /tmp
RUN /tmp/prepare-env.sh 1001

ENV APP /usr/src/app
RUN mkdir $APP
WORKDIR $APP

RUN bundle config build.nokogiri --use-system-libraries
ENV DEFAULT_DOMAIN localhost
ENV RAILS_ENV test

COPY Gemfile Gemfile.lock $APP/
RUN bundle install

# https://github.com/mikel/mail/issues/1489 - remove when fixed
RUN find /usr/local/bundle/gems/mail-2.8.0/ -type f -perm 640 -exec chmod 644 {} \;

COPY package.json yarn.lock $APP/
RUN yarn
RUN chown rails:rails $APP/
COPY --chown=rails:rails . $APP/
USER rails
RUN ./bin/webpacker

ENTRYPOINT ["vendor/docker-entrypoint.sh"]
CMD ["bash"]
