version: '3.4'
services:
  db:
    image: postgres
    ports:
      - "5432"
    environment:
      POSTGRES_PASSWORD: s3sam3
  web:
    build:
      context: .
      args:
        UID: ${UID:-1001}
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
      - "3035:3035"
    depends_on:
      - db
    user: rails
    environment:
      DD_AGENT_HOST: datadog
      JWT_SECRET: 8139a4837740e8ca5aa6809fb87912605d4ad652cb247c30096eb62413812375d4fa906bb0bee9c3aa3663b814681af7e0e68dc1a8d59f13034ddd24f7a4fefb
  datadog:
    build: datadog
    links:
      - web
    environment:
      - DD_API_KEY
      - DD_SITE=datadoghq.eu
      - DD_ENV=dev
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_LOGS_CONFIG_DOCKER_CONTAINER_USE_FILE=true
      - DD_CONTAINER_EXCLUDE=name:name_datadog
      - DD_LOG_LEVEL=WARN
    volumes:
      - ./log:/log
