apiVersion: v1
kind: PersistentVolume
metadata:
  name: name-pn-storage-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/storage"
