---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/v1/users/{slug}":
    parameters:
    - name: slug
      in: path
      description: The slug of the user you want to retrieve
      example: abby-yates
      required: true
      schema:
        type: string
    get:
      summary: show user
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/User"
        '404':
          description: not found
basePath: "/api"
servers:
- url: "/api"
components:
  securitySchemes:
    apiKey:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Link:
      type: object
      required:
      - title
      - url
      properties:
        title:
          type: string
          description: The title of the link
          example: Twitter
        url:
          type: string
          description: The link URL
          example: https://example.com/AbbyYates
    PronounSet:
      type: object
      required:
      - nominative
      - oblique
      - possessive_determiner
      - possessive
      - reflexive
      - copula
      properties:
        nominative:
          type: string
          description: The nominative case / subject form of this pronoun
          example: they
        oblique:
          type: string
          description: The oblique case / object form of this pronoun
          example: them
        possessive_determiner:
          type: string
          description: The possessive determiner form of this pronoun
          example: their
        possessive:
          type: string
          description: The possessive (non-determiner) form of this pronoun
          example: theirs
        reflexive:
          type: string
          description: The reflexive form of this pronoun
          example: themself
        copula:
          type: string
          description: Which copula form ('is' or 'are') to use with this pronoun
          example: are
    User:
      type: object
      required:
      - slug
      - personal_name
      - full_name
      - formal_name
      - envelope_name
      properties:
        slug:
          type: string
          description: This user's unique slug
          example: abby-yates
        personal_name:
          type: string
          description: Used when addressing this user in conversation
          example: Abby
        full_name:
          type: string
          description: Used when adding this user to a list of names
          example: Abby Yates
        formal_name:
          type: string
          description: Used in formal contexts such as the opening of a letter
          example: Dr Yates
          nullable: true
        envelope_name:
          type: string
          description: Used when adding this name to an address
          example: Dr Abigail L. Yates
          nullable: true
        pronoun_sets:
          type: array
          items:
            "$ref": "#/components/schemas/PronounSet"
          minItems: 1
        pronunciation_of:
          type: string
          enum:
          - full_name
          - personal_name
          - formal_name
          - envelope_name
          description: Which of the fields the pronunciation fields (phonetic, pronunciation
            and ipa) relate to
        phonetic:
          type: string
          description: Phonetic pronunciation
          example: A-bee YAYTS
          nullable: true
        ipa:
          type: string
          description: International Phonetic Alphabet pronunciation
          example: ˈabi jeɪts
          nullable: true
        pronunciation:
          type: string
          format: uri
          description: 'URL of an audio clip of the pronunciation. **Note**: May be
            a relative URL and may redirect.'
          example: "/rails/active_storage/blobs/redirect/xxx.wav"
          nullable: true
        likeness:
          type: string
          format: uri
          description: 'URL of an image of the user''s likeness. **Note**: May be
            a relative URL and may redirect.'
          example: "/rails/active_storage/blobs/redirect/yyy.jpg"
          nullable: true
        links:
          type: array
          items:
            "$ref": "#/components/schemas/Link"
