---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/v1/users/{slug}":
    parameters:
    - name: slug
      in: path
      description: The slug of the user you want to retrieve
      example: abby-yates
      required: true
      schema:
        type: string
    get:
      summary: show user
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/User"
        '404':
          description: not found
basePath: "/api"
servers:
- url: "/api"
components:
  schemas:
    User:
      type: object
      required:
      - slug
      - personal_name
      - full_name
      - formal_name
      - envelope_name
      properties:
        slug:
          type: string
          description: This user's unique slug
          example: abby-yates
        personal_name:
          type: string
          description: Used when addressing this user in conversation
          example: Abby
        full_name:
          type: string
          description: The name this user uses on a list of names
          example: Abby Yates
        formal_name:
          type: string
          description: Used in formal contexts such as the opening of a letter
          example: Dr Yates
          nullable: true
        envelope_name:
          type: string
          description: Used when adding this name to an address
          example: Dr Abigail L. Yates
          nullable: true
