default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: s3sam3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: name_pn_development
test:
  <<: *default
  database: name_pn_test
production:
  <<: *default
  database: name_pn_production
