default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("POSTGRES_HOST") { "postgresql" } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "postgres" } %> 
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "CHANGE-ME" } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: name_pn_development
test:
  <<: *default
  database: name_pn_test
production:
  <<: *default
  database: name_pn_production
