default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRESQL_SERVICE_HOST", nil) %>
  username: postgres
  password: <%= ENV.fetch("POSTGRES_PASSWORD", nil) %>
development:
  <<: *default
  database: name_pn_development
test:
  <<: *default
  database: name_pn_test
production:
  <<: *default
  database: name_pn_production
