# frozen_string_literal: true

require 'rails_helper'

RSpec.configure do |config|
  # Specify a root folder where Swagger JSON files are generated
  # NOTE: If you're using the rswag-api to serve API descriptions, you'll need
  # to ensure that it's configured to serve Swagger from the same folder
  config.swagger_root = Rails.root.join('swagger').to_s

  # Define one or more Swagger documents and provide global metadata for each one
  # When you run the 'rswag:specs:swaggerize' rake task, the complete Swagger will
  # be generated at the provided relative path under swagger_root
  # By default, the operations defined in spec files are added to the first
  # document below. You can override this behavior by adding a swagger_doc tag to the
  # the root example_group in your specs, e.g. describe '...', swagger_doc: 'v2/swagger.json'
  config.swagger_docs = {
    'v1/swagger.yaml' => {
      openapi: '3.0.1',
      info: {
        title: 'name.pn API',
        description: <<~MD,
        ## Welcome to the name.pn API
        
        Here you can get programmatic access to name.pn profiles for use in your
        own applications.
        
        For example, you may have an application that sends emails and you want
        to use a person's formal_name to address them, instead of asking them for
        a title, which is not appropriate for many users.
        
        ### API keys
        
        You will need an API key to access this API. These can be generated by
        visiting [your account settings](/users/edit) and filling in the form.
        
        You can supply your key in the headers like this:
        
        ```
        Authentication: Bearer <your_key>
        ```
        
        You can test the live API endpoints in the documentation below. To do
        so, please click the button marked *Authorize* and enter your API key
        there.
        
        ### Terms of use
        
        Use of the name.pn API is subject to the [name.pn terms and conditions 
        of use](/pages/terms), including the prohibited uses in Section 4.
        
        Use of this API is provided with no guarantees. Please be considerate in
        how you use it, including caching responses if you're making frequent
        calls.
        
        There are no fixed usage limits, but your API key ID is logged with
        every request and we reserve the right to disable clients that are not
        being considerate in their usage.
        
        As a guideline, please consider 3600 calls per hour to this API as a
        reasonable limit that we would not impose any restrictions on. If you
        need more than this, please contact us for a commercial agreement.
        
        Usage of this API is currently provided at no charge. We reserve the
        right to introduce charges to this API as this product matures.
        MD
        version: 'v1'
      },
      paths: {},
      servers: [{url: '/api'}],
      components: {
        securitySchemes: {
          jwt: {
            type: :http,
            scheme: :bearer,
            bearerFormat: :JWT
          }
        },
        schemas: {
          Link: LinkBlueprint::SCHEMA,
          PronounSet: PronounSetBlueprint::SCHEMA,
          User: UserBlueprint::SCHEMA
        }
      }
    }
  }

  # Specify the format of the output Swagger file when running 'rswag:specs:swaggerize'.
  # The swagger_docs configuration option has the filename including format in
  # the key, this may want to be changed to avoid putting yaml in json files.
  # Defaults to json. Accepts ':json' and ':yaml'.
  config.swagger_format = :yaml
end

def needs_login
  security [jwt: []]
  let(:client) { create :client }
  let(:Authorization) { jwt client }
  response 401, 'not logged in' do
    let(:Authorization) { nil }
    run_test!
  end
end
