name: audits
run-name: ${{ github.actor }} is running dependency audits
on: [push]
permissions:
  contents: read
jobs:
  ruby:
    name: Ruby (bundle audit)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '4.0.1'
          bundler-cache: true
      - name: Run bundle audit
        run: bundle exec bundle-audit check --update
  js:
    name: JS (bun audit)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Bun
        uses: oven-sh/setup-bun@v2
      - name: Install bun dependencies
        run: bun install --frozen-lockfile
      - name: Run bun audit
        run: bun audit
